### ISSUE TITLE
DiscordSRV 

### ISSUE THREAD

**Issue by Schmilko** [Sxtanna/vox-chat#1]
Is it possible Voxchat is conflicting with DiscordSRV? On my test server without VoxChat DiscordSRV is printing messages from Minecraft to the Discord channel fine, but not on the one with VoxChat.

**Comment by Schmilko** [comment]
canceling chat events

**Comment by Sxtanna** [comment]
That is possible, yes.

DiscordSRV listen to chat events at the monitor priority, vox-chat listens at high. 

It does seem to have a config option for specifically this:
https://github.com/DiscordSRV/DiscordSRV/blob/2beb615ff51fc9e03edf79a2e06b88aca973e9ea/src/main/java/github/scarsz/discordsrv/DiscordSRV.java#L1224

Try setting `RespectChatPlugins` to `false` in your DiscordSRV configuration.

**Comment by Schmilko** [comment]
Thanks, that fixed it. Can you add me back on Discord rhizo#7034

**Comment by Sxtanna** [comment]
Sure.
